FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "ChessGame2/ChessGame2.csproj"
RUN dotnet build "ChessGame2/ChessGame2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ChessGame2/ChessGame2.csproj" -c Release -o /app/publish

EXPOSE 8181

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ChessGame2.dll"]