version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__AppDbContext=Host=database;Database=SigmaChess;Username=ted;Password=ted
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ted
      POSTGRES_PASSWORD: ted
      POSTGRES_DB: SigmaChess
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
